// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql"
)

type CentralstoreMetadatum struct {
	Key   string
	Value string
}

type LocalSession struct {
	ID                    string
	RowVersion            int64
	Adapter               string
	ConversationRef       sql.NullString
	CommandJson           string
	Cwd                   string
	WorkspaceRoot         sql.NullString
	RemotesJson           string
	Slug                  sql.NullString
	SlugBase              sql.NullString
	ShellTitle            sql.NullString
	AdapterTitle          sql.NullString
	Subtitle              sql.NullString
	Active                int64
	Interrupted           int64
	Unread                int64
	HasError              int64
	StatusReported        int64
	CreatedAtMs           int64
	StartedAtMs           sql.NullInt64
	ExitedAtMs            sql.NullInt64
	LastActivityAtMs      sql.NullInt64
	DismissedAtMs         sql.NullInt64
	ExitCode              sql.NullInt64
	TerminalCols          sql.NullInt64
	TerminalRows          sql.NullInt64
	ParentSessionID       sql.NullString
	DriveMode             string
	LaunchedFromSessionID sql.NullString
	UnreadToken           string
}

type ManualPeer struct {
	ID          int64
	RowVersion  int64
	Name        string
	Url         string
	Token       sql.NullString
	NodeID      sql.NullString
	CreatedAtMs int64
	UpdatedAtMs int64
}

type ProjectEntry struct {
	ID           int64
	SidebarOrder int64
	EntryKind    string
	Slug         string
	PeerKey      sql.NullString
	NodeID       sql.NullString
	CreatedAtMs  int64
	UpdatedAtMs  int64
}

type ProjectMatchRule struct {
	ID             int64
	ProjectEntryID int64
	RuleOrder      int64
	Path           sql.NullString
	Remote         sql.NullString
	Exact          int64
}

type ProjectPlacement struct {
	ID                  int64
	ProjectEntryID      int64
	LocalSessionID      sql.NullString
	LocalPeerKey        sql.NullString
	PeerSessionID       sql.NullString
	PeerParentSessionID sql.NullString
	SiblingScope        string
	Position            int64
}
