// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package db

import (
	"context"
	"database/sql"
)

const acknowledgeSessionAtVersion = `-- name: AcknowledgeSessionAtVersion :execrows
UPDATE local_sessions
SET unread = 0, row_version = row_version + 1
WHERE id = ? AND row_version = ? AND unread <> 0
`

type AcknowledgeSessionAtVersionParams struct {
	ID         string
	RowVersion int64
}

func (q *Queries) AcknowledgeSessionAtVersion(ctx context.Context, arg AcknowledgeSessionAtVersionParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, acknowledgeSessionAtVersion, arg.ID, arg.RowVersion)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const acknowledgeSessionTokenAtVersion = `-- name: AcknowledgeSessionTokenAtVersion :execrows
UPDATE local_sessions
SET unread = 0, row_version = row_version + 1
WHERE id = ? AND row_version = ? AND unread_token = ? AND unread <> 0
`

type AcknowledgeSessionTokenAtVersionParams struct {
	ID          string
	RowVersion  int64
	UnreadToken string
}

func (q *Queries) AcknowledgeSessionTokenAtVersion(ctx context.Context, arg AcknowledgeSessionTokenAtVersionParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, acknowledgeSessionTokenAtVersion, arg.ID, arg.RowVersion, arg.UnreadToken)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const clearDirectChildParents = `-- name: ClearDirectChildParents :execrows
UPDATE local_sessions
SET parent_session_id = NULL, row_version = row_version + 1
WHERE parent_session_id = ?
`

func (q *Queries) ClearDirectChildParents(ctx context.Context, parentSessionID sql.NullString) (int64, error) {
	result, err := q.db.ExecContext(ctx, clearDirectChildParents, parentSessionID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteLocalPeerPlacement = `-- name: DeleteLocalPeerPlacement :execrows
DELETE FROM project_placements
WHERE local_peer_key = ? AND peer_session_id = ?
`

type DeleteLocalPeerPlacementParams struct {
	LocalPeerKey  sql.NullString
	PeerSessionID sql.NullString
}

func (q *Queries) DeleteLocalPeerPlacement(ctx context.Context, arg DeleteLocalPeerPlacementParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteLocalPeerPlacement, arg.LocalPeerKey, arg.PeerSessionID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteLocalPeerPlacements = `-- name: DeleteLocalPeerPlacements :execrows
DELETE FROM project_placements WHERE local_peer_key = ?
`

func (q *Queries) DeleteLocalPeerPlacements(ctx context.Context, localPeerKey sql.NullString) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteLocalPeerPlacements, localPeerKey)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteLocalSessionPlacement = `-- name: DeleteLocalSessionPlacement :execrows
DELETE FROM project_placements WHERE local_session_id = ?
`

func (q *Queries) DeleteLocalSessionPlacement(ctx context.Context, localSessionID sql.NullString) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteLocalSessionPlacement, localSessionID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteManualPeerByName = `-- name: DeleteManualPeerByName :execrows
DELETE FROM manual_peers WHERE name = ?
`

func (q *Queries) DeleteManualPeerByName(ctx context.Context, name string) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteManualPeerByName, name)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteProjectEntry = `-- name: DeleteProjectEntry :execrows
DELETE FROM project_entries WHERE id = ?
`

func (q *Queries) DeleteProjectEntry(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteProjectEntry, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteProjectRules = `-- name: DeleteProjectRules :exec
DELETE FROM project_match_rules WHERE project_entry_id = ?
`

func (q *Queries) DeleteProjectRules(ctx context.Context, projectEntryID int64) error {
	_, err := q.db.ExecContext(ctx, deleteProjectRules, projectEntryID)
	return err
}

const deleteSessionAtVersion = `-- name: DeleteSessionAtVersion :execrows
DELETE FROM local_sessions WHERE id = ? AND row_version = ?
`

type DeleteSessionAtVersionParams struct {
	ID         string
	RowVersion int64
}

func (q *Queries) DeleteSessionAtVersion(ctx context.Context, arg DeleteSessionAtVersionParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteSessionAtVersion, arg.ID, arg.RowVersion)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const dismissSession = `-- name: DismissSession :execrows
UPDATE local_sessions
SET dismissed_at_ms = ?1, row_version = row_version + 1
WHERE id = ?2 AND dismissed_at_ms IS NULL
`

type DismissSessionParams struct {
	DismissedAtMs sql.NullInt64
	ID            string
}

func (q *Queries) DismissSession(ctx context.Context, arg DismissSessionParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, dismissSession, arg.DismissedAtMs, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const finalizeLocalPeerPlacement = `-- name: FinalizeLocalPeerPlacement :execrows
UPDATE project_placements
SET project_entry_id = ?, peer_parent_session_id = ?, sibling_scope = ?, position = ?
WHERE id = ? AND local_session_id IS NULL
`

type FinalizeLocalPeerPlacementParams struct {
	ProjectEntryID      int64
	PeerParentSessionID sql.NullString
	SiblingScope        string
	Position            int64
	ID                  int64
}

func (q *Queries) FinalizeLocalPeerPlacement(ctx context.Context, arg FinalizeLocalPeerPlacementParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, finalizeLocalPeerPlacement,
		arg.ProjectEntryID,
		arg.PeerParentSessionID,
		arg.SiblingScope,
		arg.Position,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const finalizeLocalPlacement = `-- name: FinalizeLocalPlacement :execrows
UPDATE project_placements
SET project_entry_id = ?, sibling_scope = ?, position = ?
WHERE id = ? AND local_session_id IS NOT NULL
`

type FinalizeLocalPlacementParams struct {
	ProjectEntryID int64
	SiblingScope   string
	Position       int64
	ID             int64
}

func (q *Queries) FinalizeLocalPlacement(ctx context.Context, arg FinalizeLocalPlacementParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, finalizeLocalPlacement,
		arg.ProjectEntryID,
		arg.SiblingScope,
		arg.Position,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const finalizeProjectEntryOrder = `-- name: FinalizeProjectEntryOrder :execrows
UPDATE project_entries SET sidebar_order = ? WHERE id = ?
`

type FinalizeProjectEntryOrderParams struct {
	SidebarOrder int64
	ID           int64
}

func (q *Queries) FinalizeProjectEntryOrder(ctx context.Context, arg FinalizeProjectEntryOrderParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, finalizeProjectEntryOrder, arg.SidebarOrder, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getMetadata = `-- name: GetMetadata :one
SELECT value FROM centralstore_metadata WHERE key = ?
`

func (q *Queries) GetMetadata(ctx context.Context, key string) (string, error) {
	row := q.db.QueryRowContext(ctx, getMetadata, key)
	var value string
	err := row.Scan(&value)
	return value, err
}

const getSession = `-- name: GetSession :one
SELECT id, row_version, adapter, conversation_ref, command_json, cwd, workspace_root, remotes_json, slug, slug_base, shell_title, adapter_title, subtitle, active, interrupted, unread, has_error, status_reported, created_at_ms, started_at_ms, exited_at_ms, last_activity_at_ms, dismissed_at_ms, exit_code, terminal_cols, terminal_rows, parent_session_id, drive_mode, launched_from_session_id, unread_token FROM local_sessions WHERE id = ?
`

func (q *Queries) GetSession(ctx context.Context, id string) (LocalSession, error) {
	row := q.db.QueryRowContext(ctx, getSession, id)
	var i LocalSession
	err := row.Scan(
		&i.ID,
		&i.RowVersion,
		&i.Adapter,
		&i.ConversationRef,
		&i.CommandJson,
		&i.Cwd,
		&i.WorkspaceRoot,
		&i.RemotesJson,
		&i.Slug,
		&i.SlugBase,
		&i.ShellTitle,
		&i.AdapterTitle,
		&i.Subtitle,
		&i.Active,
		&i.Interrupted,
		&i.Unread,
		&i.HasError,
		&i.StatusReported,
		&i.CreatedAtMs,
		&i.StartedAtMs,
		&i.ExitedAtMs,
		&i.LastActivityAtMs,
		&i.DismissedAtMs,
		&i.ExitCode,
		&i.TerminalCols,
		&i.TerminalRows,
		&i.ParentSessionID,
		&i.DriveMode,
		&i.LaunchedFromSessionID,
		&i.UnreadToken,
	)
	return i, err
}

const insertLocalPeerPlacement = `-- name: InsertLocalPeerPlacement :one
INSERT INTO project_placements
(project_entry_id, local_peer_key, peer_session_id, peer_parent_session_id,
 sibling_scope, position)
VALUES (?, ?, ?, ?, ?, ?)
RETURNING id
`

type InsertLocalPeerPlacementParams struct {
	ProjectEntryID      int64
	LocalPeerKey        sql.NullString
	PeerSessionID       sql.NullString
	PeerParentSessionID sql.NullString
	SiblingScope        string
	Position            int64
}

func (q *Queries) InsertLocalPeerPlacement(ctx context.Context, arg InsertLocalPeerPlacementParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, insertLocalPeerPlacement,
		arg.ProjectEntryID,
		arg.LocalPeerKey,
		arg.PeerSessionID,
		arg.PeerParentSessionID,
		arg.SiblingScope,
		arg.Position,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const insertLocalPlacement = `-- name: InsertLocalPlacement :one
INSERT INTO project_placements
(project_entry_id, local_session_id, sibling_scope, position)
VALUES (?, ?, ?, ?)
RETURNING id
`

type InsertLocalPlacementParams struct {
	ProjectEntryID int64
	LocalSessionID sql.NullString
	SiblingScope   string
	Position       int64
}

func (q *Queries) InsertLocalPlacement(ctx context.Context, arg InsertLocalPlacementParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, insertLocalPlacement,
		arg.ProjectEntryID,
		arg.LocalSessionID,
		arg.SiblingScope,
		arg.Position,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const insertManualPeer = `-- name: InsertManualPeer :one
INSERT INTO manual_peers (name, url, token, node_id, created_at_ms, updated_at_ms)
VALUES (?, ?, ?, ?, ?, ?)
RETURNING id, row_version, name, url, token, node_id, created_at_ms, updated_at_ms
`

type InsertManualPeerParams struct {
	Name        string
	Url         string
	Token       sql.NullString
	NodeID      sql.NullString
	CreatedAtMs int64
	UpdatedAtMs int64
}

func (q *Queries) InsertManualPeer(ctx context.Context, arg InsertManualPeerParams) (ManualPeer, error) {
	row := q.db.QueryRowContext(ctx, insertManualPeer,
		arg.Name,
		arg.Url,
		arg.Token,
		arg.NodeID,
		arg.CreatedAtMs,
		arg.UpdatedAtMs,
	)
	var i ManualPeer
	err := row.Scan(
		&i.ID,
		&i.RowVersion,
		&i.Name,
		&i.Url,
		&i.Token,
		&i.NodeID,
		&i.CreatedAtMs,
		&i.UpdatedAtMs,
	)
	return i, err
}

const insertProjectEntry = `-- name: InsertProjectEntry :one
INSERT INTO project_entries
(sidebar_order, entry_kind, slug, peer_key, node_id, created_at_ms, updated_at_ms)
VALUES (?, ?, ?, ?, ?, ?, ?)
RETURNING id
`

type InsertProjectEntryParams struct {
	SidebarOrder int64
	EntryKind    string
	Slug         string
	PeerKey      sql.NullString
	NodeID       sql.NullString
	CreatedAtMs  int64
	UpdatedAtMs  int64
}

func (q *Queries) InsertProjectEntry(ctx context.Context, arg InsertProjectEntryParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, insertProjectEntry,
		arg.SidebarOrder,
		arg.EntryKind,
		arg.Slug,
		arg.PeerKey,
		arg.NodeID,
		arg.CreatedAtMs,
		arg.UpdatedAtMs,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const insertProjectRule = `-- name: InsertProjectRule :exec
INSERT INTO project_match_rules
(project_entry_id, rule_order, path, remote, exact)
VALUES (?, ?, ?, ?, ?)
`

type InsertProjectRuleParams struct {
	ProjectEntryID int64
	RuleOrder      int64
	Path           sql.NullString
	Remote         sql.NullString
	Exact          int64
}

func (q *Queries) InsertProjectRule(ctx context.Context, arg InsertProjectRuleParams) error {
	_, err := q.db.ExecContext(ctx, insertProjectRule,
		arg.ProjectEntryID,
		arg.RuleOrder,
		arg.Path,
		arg.Remote,
		arg.Exact,
	)
	return err
}

const insertSession = `-- name: InsertSession :one
INSERT INTO local_sessions (
    id, adapter, drive_mode, conversation_ref, command_json, cwd, workspace_root,
    remotes_json, slug, slug_base, shell_title, adapter_title, subtitle,
    active, interrupted, unread, unread_token, has_error, status_reported, created_at_ms, started_at_ms,
    exited_at_ms, last_activity_at_ms, exit_code, terminal_cols, terminal_rows,
    parent_session_id, launched_from_session_id
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, row_version, adapter, conversation_ref, command_json, cwd, workspace_root, remotes_json, slug, slug_base, shell_title, adapter_title, subtitle, active, interrupted, unread, has_error, status_reported, created_at_ms, started_at_ms, exited_at_ms, last_activity_at_ms, dismissed_at_ms, exit_code, terminal_cols, terminal_rows, parent_session_id, drive_mode, launched_from_session_id, unread_token
`

type InsertSessionParams struct {
	ID                    string
	Adapter               string
	DriveMode             string
	ConversationRef       sql.NullString
	CommandJson           string
	Cwd                   string
	WorkspaceRoot         sql.NullString
	RemotesJson           string
	Slug                  sql.NullString
	SlugBase              sql.NullString
	ShellTitle            sql.NullString
	AdapterTitle          sql.NullString
	Subtitle              sql.NullString
	Active                int64
	Interrupted           int64
	Unread                int64
	UnreadToken           string
	HasError              int64
	StatusReported        int64
	CreatedAtMs           int64
	StartedAtMs           sql.NullInt64
	ExitedAtMs            sql.NullInt64
	LastActivityAtMs      sql.NullInt64
	ExitCode              sql.NullInt64
	TerminalCols          sql.NullInt64
	TerminalRows          sql.NullInt64
	ParentSessionID       sql.NullString
	LaunchedFromSessionID sql.NullString
}

func (q *Queries) InsertSession(ctx context.Context, arg InsertSessionParams) (LocalSession, error) {
	row := q.db.QueryRowContext(ctx, insertSession,
		arg.ID,
		arg.Adapter,
		arg.DriveMode,
		arg.ConversationRef,
		arg.CommandJson,
		arg.Cwd,
		arg.WorkspaceRoot,
		arg.RemotesJson,
		arg.Slug,
		arg.SlugBase,
		arg.ShellTitle,
		arg.AdapterTitle,
		arg.Subtitle,
		arg.Active,
		arg.Interrupted,
		arg.Unread,
		arg.UnreadToken,
		arg.HasError,
		arg.StatusReported,
		arg.CreatedAtMs,
		arg.StartedAtMs,
		arg.ExitedAtMs,
		arg.LastActivityAtMs,
		arg.ExitCode,
		arg.TerminalCols,
		arg.TerminalRows,
		arg.ParentSessionID,
		arg.LaunchedFromSessionID,
	)
	var i LocalSession
	err := row.Scan(
		&i.ID,
		&i.RowVersion,
		&i.Adapter,
		&i.ConversationRef,
		&i.CommandJson,
		&i.Cwd,
		&i.WorkspaceRoot,
		&i.RemotesJson,
		&i.Slug,
		&i.SlugBase,
		&i.ShellTitle,
		&i.AdapterTitle,
		&i.Subtitle,
		&i.Active,
		&i.Interrupted,
		&i.Unread,
		&i.HasError,
		&i.StatusReported,
		&i.CreatedAtMs,
		&i.StartedAtMs,
		&i.ExitedAtMs,
		&i.LastActivityAtMs,
		&i.DismissedAtMs,
		&i.ExitCode,
		&i.TerminalCols,
		&i.TerminalRows,
		&i.ParentSessionID,
		&i.DriveMode,
		&i.LaunchedFromSessionID,
		&i.UnreadToken,
	)
	return i, err
}

const listAdapterSlugs = `-- name: ListAdapterSlugs :many
SELECT id, slug FROM local_sessions
WHERE adapter = ? AND slug IS NOT NULL AND slug <> ''
`

type ListAdapterSlugsRow struct {
	ID   string
	Slug sql.NullString
}

// Slug-occupancy probe for allocation. The predicate matches the partial
// unique index local_sessions_adapter_slug_unique_idx, so this is an index
// range scan instead of a full-table hydration.
func (q *Queries) ListAdapterSlugs(ctx context.Context, adapter string) ([]ListAdapterSlugsRow, error) {
	rows, err := q.db.QueryContext(ctx, listAdapterSlugs, adapter)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAdapterSlugsRow
	for rows.Next() {
		var i ListAdapterSlugsRow
		if err := rows.Scan(&i.ID, &i.Slug); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listManualPeers = `-- name: ListManualPeers :many
SELECT id, row_version, name, url, token, node_id, created_at_ms, updated_at_ms FROM manual_peers ORDER BY id
`

func (q *Queries) ListManualPeers(ctx context.Context) ([]ManualPeer, error) {
	rows, err := q.db.QueryContext(ctx, listManualPeers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ManualPeer
	for rows.Next() {
		var i ManualPeer
		if err := rows.Scan(
			&i.ID,
			&i.RowVersion,
			&i.Name,
			&i.Url,
			&i.Token,
			&i.NodeID,
			&i.CreatedAtMs,
			&i.UpdatedAtMs,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPlacements = `-- name: ListPlacements :many
SELECT p.id, p.project_entry_id, p.local_session_id, p.local_peer_key,
       p.peer_session_id, p.peer_parent_session_id, p.sibling_scope, p.position,
       COALESCE(s.created_at_ms, 0) AS local_created_at_ms,
       s.parent_session_id
FROM project_placements p
LEFT JOIN local_sessions s ON s.id = p.local_session_id
ORDER BY p.project_entry_id, p.sibling_scope, p.position, p.id
`

type ListPlacementsRow struct {
	ID                  int64
	ProjectEntryID      int64
	LocalSessionID      sql.NullString
	LocalPeerKey        sql.NullString
	PeerSessionID       sql.NullString
	PeerParentSessionID sql.NullString
	SiblingScope        string
	Position            int64
	LocalCreatedAtMs    int64
	ParentSessionID     sql.NullString
}

func (q *Queries) ListPlacements(ctx context.Context) ([]ListPlacementsRow, error) {
	rows, err := q.db.QueryContext(ctx, listPlacements)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPlacementsRow
	for rows.Next() {
		var i ListPlacementsRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectEntryID,
			&i.LocalSessionID,
			&i.LocalPeerKey,
			&i.PeerSessionID,
			&i.PeerParentSessionID,
			&i.SiblingScope,
			&i.Position,
			&i.LocalCreatedAtMs,
			&i.ParentSessionID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjectEntries = `-- name: ListProjectEntries :many
SELECT id, sidebar_order, entry_kind, slug, peer_key, node_id, created_at_ms, updated_at_ms FROM project_entries ORDER BY sidebar_order
`

func (q *Queries) ListProjectEntries(ctx context.Context) ([]ProjectEntry, error) {
	rows, err := q.db.QueryContext(ctx, listProjectEntries)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ProjectEntry
	for rows.Next() {
		var i ProjectEntry
		if err := rows.Scan(
			&i.ID,
			&i.SidebarOrder,
			&i.EntryKind,
			&i.Slug,
			&i.PeerKey,
			&i.NodeID,
			&i.CreatedAtMs,
			&i.UpdatedAtMs,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjectRules = `-- name: ListProjectRules :many
SELECT id, project_entry_id, rule_order, path, remote, exact FROM project_match_rules ORDER BY project_entry_id, rule_order
`

func (q *Queries) ListProjectRules(ctx context.Context) ([]ProjectMatchRule, error) {
	rows, err := q.db.QueryContext(ctx, listProjectRules)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ProjectMatchRule
	for rows.Next() {
		var i ProjectMatchRule
		if err := rows.Scan(
			&i.ID,
			&i.ProjectEntryID,
			&i.RuleOrder,
			&i.Path,
			&i.Remote,
			&i.Exact,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSessions = `-- name: ListSessions :many
SELECT id, row_version, adapter, conversation_ref, command_json, cwd, workspace_root, remotes_json, slug, slug_base, shell_title, adapter_title, subtitle, active, interrupted, unread, has_error, status_reported, created_at_ms, started_at_ms, exited_at_ms, last_activity_at_ms, dismissed_at_ms, exit_code, terminal_cols, terminal_rows, parent_session_id, drive_mode, launched_from_session_id, unread_token FROM local_sessions ORDER BY id
`

func (q *Queries) ListSessions(ctx context.Context) ([]LocalSession, error) {
	rows, err := q.db.QueryContext(ctx, listSessions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LocalSession
	for rows.Next() {
		var i LocalSession
		if err := rows.Scan(
			&i.ID,
			&i.RowVersion,
			&i.Adapter,
			&i.ConversationRef,
			&i.CommandJson,
			&i.Cwd,
			&i.WorkspaceRoot,
			&i.RemotesJson,
			&i.Slug,
			&i.SlugBase,
			&i.ShellTitle,
			&i.AdapterTitle,
			&i.Subtitle,
			&i.Active,
			&i.Interrupted,
			&i.Unread,
			&i.HasError,
			&i.StatusReported,
			&i.CreatedAtMs,
			&i.StartedAtMs,
			&i.ExitedAtMs,
			&i.LastActivityAtMs,
			&i.DismissedAtMs,
			&i.ExitCode,
			&i.TerminalCols,
			&i.TerminalRows,
			&i.ParentSessionID,
			&i.DriveMode,
			&i.LaunchedFromSessionID,
			&i.UnreadToken,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const localSessionPlacementFacts = `-- name: LocalSessionPlacementFacts :one
SELECT created_at_ms, parent_session_id
FROM local_sessions WHERE id = ?
`

type LocalSessionPlacementFactsRow struct {
	CreatedAtMs     int64
	ParentSessionID sql.NullString
}

func (q *Queries) LocalSessionPlacementFacts(ctx context.Context, id string) (LocalSessionPlacementFactsRow, error) {
	row := q.db.QueryRowContext(ctx, localSessionPlacementFacts, id)
	var i LocalSessionPlacementFactsRow
	err := row.Scan(&i.CreatedAtMs, &i.ParentSessionID)
	return i, err
}

const ownedProjectExists = `-- name: OwnedProjectExists :one
SELECT EXISTS(
    SELECT 1 FROM project_entries WHERE id = ? AND entry_kind = 'owned'
)
`

func (q *Queries) OwnedProjectExists(ctx context.Context, id int64) (bool, error) {
	row := q.db.QueryRowContext(ctx, ownedProjectExists, id)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const parkPlacement = `-- name: ParkPlacement :execrows
UPDATE project_placements SET sibling_scope = ?, position = 0 WHERE id = ?
`

type ParkPlacementParams struct {
	SiblingScope string
	ID           int64
}

func (q *Queries) ParkPlacement(ctx context.Context, arg ParkPlacementParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, parkPlacement, arg.SiblingScope, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const parkProjectEntries = `-- name: ParkProjectEntries :exec
UPDATE project_entries SET sidebar_order = sidebar_order + ?
`

func (q *Queries) ParkProjectEntries(ctx context.Context, sidebarOrder int64) error {
	_, err := q.db.ExecContext(ctx, parkProjectEntries, sidebarOrder)
	return err
}

const parkProjectEntrySlug = `-- name: ParkProjectEntrySlug :execrows
UPDATE project_entries SET slug = ? WHERE id = ?
`

type ParkProjectEntrySlugParams struct {
	Slug string
	ID   int64
}

func (q *Queries) ParkProjectEntrySlug(ctx context.Context, arg ParkProjectEntrySlugParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, parkProjectEntrySlug, arg.Slug, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const placementCount = `-- name: PlacementCount :one
SELECT COUNT(*) FROM project_placements
`

func (q *Queries) PlacementCount(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, placementCount)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const putMetadata = `-- name: PutMetadata :exec
INSERT INTO centralstore_metadata (key, value) VALUES (?, ?)
ON CONFLICT (key) DO UPDATE SET value = excluded.value
`

type PutMetadataParams struct {
	Key   string
	Value string
}

func (q *Queries) PutMetadata(ctx context.Context, arg PutMetadataParams) error {
	_, err := q.db.ExecContext(ctx, putMetadata, arg.Key, arg.Value)
	return err
}

const sessionVersion = `-- name: SessionVersion :one
SELECT row_version FROM local_sessions WHERE id = ?
`

func (q *Queries) SessionVersion(ctx context.Context, id string) (int64, error) {
	row := q.db.QueryRowContext(ctx, sessionVersion, id)
	var row_version int64
	err := row.Scan(&row_version)
	return row_version, err
}

const setSessionParent = `-- name: SetSessionParent :execrows
UPDATE local_sessions
SET parent_session_id = ?, row_version = row_version + 1
WHERE id = ? AND parent_session_id IS NOT ?
`

type SetSessionParentParams struct {
	ParentSessionID   sql.NullString
	ID                string
	ParentSessionID_2 sql.NullString
}

func (q *Queries) SetSessionParent(ctx context.Context, arg SetSessionParentParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, setSessionParent, arg.ParentSessionID, arg.ID, arg.ParentSessionID_2)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const sweepSessionDead = `-- name: SweepSessionDead :execrows
UPDATE local_sessions
SET exited_at_ms = ?1,
    row_version = row_version + 1
WHERE id = ?2 AND exited_at_ms IS NULL
`

type SweepSessionDeadParams struct {
	SweptAtMs sql.NullInt64
	ID        string
}

func (q *Queries) SweepSessionDead(ctx context.Context, arg SweepSessionDeadParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, sweepSessionDead, arg.SweptAtMs, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const temporaryPlacementCount = `-- name: TemporaryPlacementCount :one
SELECT COUNT(*) FROM project_placements WHERE sibling_scope LIKE '~:%'
`

func (q *Queries) TemporaryPlacementCount(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, temporaryPlacementCount)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const updateCommonFacts = `-- name: UpdateCommonFacts :execrows
UPDATE local_sessions SET
    row_version = row_version + 1,
    adapter = ?, conversation_ref = ?, command_json = ?, cwd = ?,
    workspace_root = ?, remotes_json = ?, slug = ?, slug_base = ?, shell_title = ?,
    adapter_title = ?, subtitle = ?, active = ?, interrupted = ?, unread = ?, unread_token = ?, has_error = ?,
    status_reported = ?, started_at_ms = ?, exited_at_ms = ?,
    last_activity_at_ms = ?, exit_code = ?, terminal_cols = ?, terminal_rows = ?
WHERE id = ? AND row_version = ?
`

type UpdateCommonFactsParams struct {
	Adapter          string
	ConversationRef  sql.NullString
	CommandJson      string
	Cwd              string
	WorkspaceRoot    sql.NullString
	RemotesJson      string
	Slug             sql.NullString
	SlugBase         sql.NullString
	ShellTitle       sql.NullString
	AdapterTitle     sql.NullString
	Subtitle         sql.NullString
	Active           int64
	Interrupted      int64
	Unread           int64
	UnreadToken      string
	HasError         int64
	StatusReported   int64
	StartedAtMs      sql.NullInt64
	ExitedAtMs       sql.NullInt64
	LastActivityAtMs sql.NullInt64
	ExitCode         sql.NullInt64
	TerminalCols     sql.NullInt64
	TerminalRows     sql.NullInt64
	ID               string
	RowVersion       int64
}

func (q *Queries) UpdateCommonFacts(ctx context.Context, arg UpdateCommonFactsParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateCommonFacts,
		arg.Adapter,
		arg.ConversationRef,
		arg.CommandJson,
		arg.Cwd,
		arg.WorkspaceRoot,
		arg.RemotesJson,
		arg.Slug,
		arg.SlugBase,
		arg.ShellTitle,
		arg.AdapterTitle,
		arg.Subtitle,
		arg.Active,
		arg.Interrupted,
		arg.Unread,
		arg.UnreadToken,
		arg.HasError,
		arg.StatusReported,
		arg.StartedAtMs,
		arg.ExitedAtMs,
		arg.LastActivityAtMs,
		arg.ExitCode,
		arg.TerminalCols,
		arg.TerminalRows,
		arg.ID,
		arg.RowVersion,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateManualPeer = `-- name: UpdateManualPeer :execrows
UPDATE manual_peers
SET url = ?, token = ?, node_id = ?, updated_at_ms = ?,
    row_version = row_version + 1
WHERE id = ? AND row_version = ?
`

type UpdateManualPeerParams struct {
	Url         string
	Token       sql.NullString
	NodeID      sql.NullString
	UpdatedAtMs int64
	ID          int64
	RowVersion  int64
}

// UpdateManualPeer sets token and node_id UNCONDITIONALLY. The
// unknown-not-clear merge policy (empty spec value preserves the stored
// one) lives in Go (UpsertManualPeer), which must always pass the merged
// values here; adding an explicit token-clearing flow requires revisiting
// that seam, not just the Go caller (sql review L-01).
func (q *Queries) UpdateManualPeer(ctx context.Context, arg UpdateManualPeerParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateManualPeer,
		arg.Url,
		arg.Token,
		arg.NodeID,
		arg.UpdatedAtMs,
		arg.ID,
		arg.RowVersion,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateProjectEntry = `-- name: UpdateProjectEntry :execrows
UPDATE project_entries
SET sidebar_order = ?, slug = ?, node_id = ?, updated_at_ms = ?
WHERE id = ?
`

type UpdateProjectEntryParams struct {
	SidebarOrder int64
	Slug         string
	NodeID       sql.NullString
	UpdatedAtMs  int64
	ID           int64
}

func (q *Queries) UpdateProjectEntry(ctx context.Context, arg UpdateProjectEntryParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateProjectEntry,
		arg.SidebarOrder,
		arg.Slug,
		arg.NodeID,
		arg.UpdatedAtMs,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateRunnerRegistration = `-- name: UpdateRunnerRegistration :execrows
UPDATE local_sessions SET
    row_version = row_version + 1,
    conversation_ref = ?, command_json = ?, cwd = ?, workspace_root = ?,
    remotes_json = ?, slug = ?, slug_base = ?, shell_title = ?, adapter_title = ?, subtitle = ?,
    active = ?, interrupted = ?, unread = ?, unread_token = ?, has_error = ?, status_reported = ?,
    started_at_ms = ?, exited_at_ms = ?, last_activity_at_ms = ?, exit_code = ?,
    terminal_cols = ?, terminal_rows = ?, dismissed_at_ms = NULL
WHERE id = ? AND row_version = ?
`

type UpdateRunnerRegistrationParams struct {
	ConversationRef  sql.NullString
	CommandJson      string
	Cwd              string
	WorkspaceRoot    sql.NullString
	RemotesJson      string
	Slug             sql.NullString
	SlugBase         sql.NullString
	ShellTitle       sql.NullString
	AdapterTitle     sql.NullString
	Subtitle         sql.NullString
	Active           int64
	Interrupted      int64
	Unread           int64
	UnreadToken      string
	HasError         int64
	StatusReported   int64
	StartedAtMs      sql.NullInt64
	ExitedAtMs       sql.NullInt64
	LastActivityAtMs sql.NullInt64
	ExitCode         sql.NullInt64
	TerminalCols     sql.NullInt64
	TerminalRows     sql.NullInt64
	ID               string
	RowVersion       int64
}

func (q *Queries) UpdateRunnerRegistration(ctx context.Context, arg UpdateRunnerRegistrationParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateRunnerRegistration,
		arg.ConversationRef,
		arg.CommandJson,
		arg.Cwd,
		arg.WorkspaceRoot,
		arg.RemotesJson,
		arg.Slug,
		arg.SlugBase,
		arg.ShellTitle,
		arg.AdapterTitle,
		arg.Subtitle,
		arg.Active,
		arg.Interrupted,
		arg.Unread,
		arg.UnreadToken,
		arg.HasError,
		arg.StatusReported,
		arg.StartedAtMs,
		arg.ExitedAtMs,
		arg.LastActivityAtMs,
		arg.ExitCode,
		arg.TerminalCols,
		arg.TerminalRows,
		arg.ID,
		arg.RowVersion,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
